export { default as client, unwrap, unwrapPaginated, getErrorMessage, getFieldErrors, TOKEN_KEY, USER_KEY, type ApiError } from './client'
export { authApi } from './auth.api'
export { dashboardApi } from './dashboard.api'
export { patientApi, type PatientListQuery } from './patient.api'
export { appointmentApi, type AppointmentListQuery, type AppointmentInput } from './appointment.api'
export { visitApi, type VisitListQuery, type VisitInput } from './visit.api'
export { prescriptionApi, type PrescriptionListQuery, type PrescriptionInput } from './prescription.api'
export { pharmacyApi, type MedicineListQuery, type TransactionListQuery } from './pharmacy.api'
export { labApi, type LabRequestListQuery, type LabTestListQuery, type LabRequestInput, type LabTestInput } from './lab.api'
export { wardApi, type AdmissionListQuery, type AdmissionInput, type WardInput } from './ward.api'
export { billingApi, type InvoiceListQuery, type InvoiceInput, type PaymentInput } from './billing.api'
export { insuranceApi, type ClaimListQuery, type CompanyListQuery, type PatientInsuranceListQuery } from './insurance.api'
export { reportApi, type ReportRange, type ReportType } from './report.api'
export { userApi, type UserListQuery, type RoleInput } from './user.api'
export { notificationApi } from './notification.api'
<<<<<<< HEAD
export { searchApi, type SearchHit, type SearchResults, type SearchScope } from './search.api'
=======
>>>>>>> bd5e876a8b6d8083d786a30260aa69f6332f42bf
export { miscApi, type AuditListQuery, type DoctorListQuery } from './misc.api'
