import type { ReactNode } from 'react'
import {
  Activity,
  Bell,
  Boxes,
  Building,
  CalendarDays,
  ChartColumn,
  ClipboardCheck,
  ClipboardList,
  Clock,
  FileCheck,
  FileText,
  FlaskConical,
  HeartPulse,
  Hospital,
  Percent,
  Pill,
  Receipt,
  ScrollText,
  Settings,
  ShieldCheck,
  Stethoscope,
  TrendingUp,
  TriangleAlert,
  UserCog,
  Users,
  Wallet,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/** Backend stat icon keys (normalised) → lucide icon. */
const ICONS: Record<string, LucideIcon> = {
  appointment: CalendarDays,
  appointments: CalendarDays,
  admission: Hospital,
  admissions: Hospital,
  alert: TriangleAlert,
  alerts: TriangleAlert,
  audit: ScrollText,
  balance: Receipt,
  batch: Boxes,
  batches: Boxes,
  bed: ClipboardList,
  beds: ClipboardList,
  billing: Receipt,
  building: Building,
  calendar: CalendarDays,
  claim: ClipboardCheck,
  claims: ClipboardCheck,
  collection: Wallet,
  collections: Wallet,
  consultation: ClipboardList,
  consultations: ClipboardList,
  department: Building,
  departments: Building,
  discharge: Hospital,
  discharges: Hospital,
  doctor: Stethoscope,
  doctors: Stethoscope,
  emergency: Zap,
  earning: Wallet,
  earnings: Wallet,
  growth: TrendingUp,
  health: HeartPulse,
  hospital: Building,
  income: Wallet,
  inpatient: ClipboardList,
  insurance: ShieldCheck,
  invoice: Receipt,
  invoices: Receipt,
  lab: FlaskConical,
  laboratory: FlaskConical,
  labresult: FlaskConical,
  labresults: FlaskConical,
  lowstock: Boxes,
  medicine: Pill,
  medicines: Pill,
  money: Wallet,
  notification: Bell,
  notifications: Bell,
  nurse: HeartPulse,
  nurses: HeartPulse,
  occupancy: ClipboardList,
  outstanding: Receipt,
  patient: Users,
  patients: Users,
  pending: FileText,
  percentage: Percent,
  pharmacy: Pill,
  pill: Pill,
  pills: Pill,
  policy: FileCheck,
  policies: FileCheck,
  prescription: FileText,
  prescriptions: FileText,
  queue: Clock,
  rate: Percent,
  receipt: Receipt,
  report: ChartColumn,
  reports: ChartColumn,
  revenue: Wallet,
  role: UserCog,
  roles: UserCog,
  setting: Settings,
  settings: Settings,
  stock: Boxes,
  test: FlaskConical,
  tests: FlaskConical,
  time: Clock,
  today: CalendarDays,
  trend: TrendingUp,
  user: Users,
  users: Users,
  visit: ClipboardList,
  visits: ClipboardList,
  waiting: Clock,
  ward: Building,
  wards: Building,
  wallet: Wallet,
  payment: Wallet,
  payments: Wallet,
}

const MATCHERS = Object.entries(ICONS).sort((a, b) => b[0].length - a[0].length)

function normalise(key: string): string {
  return key.toLowerCase().replace(/[^a-z0-9]/g, '')
}

/** Renders the icon a stat asks for, falling back to `Activity` for unknown keys. */
export function statIcon(key: string | null | undefined): ReactNode {
  if (!key) return <Activity size={18} />
  const normalised = normalise(key)
  const Icon =
    ICONS[normalised] ??
    MATCHERS.find(([candidate]) => normalised.includes(candidate) || candidate.includes(normalised))?.[1] ??
    Activity
  return <Icon size={18} />
}
